trainer:
  accelerator: auto
  devices: auto
  precision: "16"
  max_steps: 50000
  lr: 5e-5
  weight_decay: 0.05

unet_model:
  sequence_size: 256
  harmonic_positional_encoding_power: 7
  t_encoder_num_layers: 2

  base_channels: 64
  channel_mults: [1, 2, 4]
  num_res_blocks: 3
  norm_groups: 8
  attn_resolutions: [64]
  attn_heads: 4
  final_tanh: false
  use_input_positional_encoding: true
  xpos_encoder_num_layers: 2

  down_kernel: 4
  down_stride: 2
  down_padding: 1
  up_kernel: 4
  up_stride: 2
  up_padding: 1

  degrees_of_freedom: 5 # for t - student only

  domain: frequency
  include_other_domain: false

   # -------------------------
  # NEW FiLM conditioning fields
  # -------------------------

  # unconditional => no cond vector
  extra_cond_dim: 64

  # size of global FiLM conditioning vector
  global_cond_dim: 64

data:
  dataset_folder: "datasets/ar1"
  data_class: "DataContaminationDataManager"
  outlier_percentage: 0.01 # this is only used if the dataset is made of curves and outliers
  batch_size: 1024
  data_channels: 1

rendering:
  log_every_n_steps: 1000
  num_sampled_curves: 1000

wandb:
  project: "astrophysics noise modeling"
  name: "gaussian prior - data contamination 1%"
  wandb_mode: online

loss_function:
  include_contrastive_loss: True
  include_consistency_loss: True
  
lightning_wrapper: "GaussianPriorFlowMatching"